In [267]:
import pandas as pd
import numpy as np
df = pd.read_excel('C:/Users/Student/Desktop/人口結構/人口數、戶數、性別比/台北_人口數、性別比/104年1-12月各區人口數.ods',sheet_name='1月')

In [268]:
df

,臺北市 104 年1 月 各行政區戶籍人口數、戶數統計表,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8
0,區別,里數,NaN,鄰數,NaN,戶數,人口數,NaN,NaN
1,NaN,現有門牌,戶籍登記,現有門牌,戶籍登記,NaN,合計,男,女
2,總計,456,456,9571,9556,1037834,2704133,1296292,1407841
3,松山,33,33,762,760,80051,210433,99375,111058
4,信義,41,41,911,908,89207,229854,110258,119596
5,大安,53,53,1025,1024,120229,313926,146965,166961
6,中山,42,42,869,867,98459,230833,107811,123022
7,中正,31,31,583,583,65110,163403,78143,85260
8,大同,25,25,524,522,51197,131036,64042,66994
9,萬華,36,36,722,722,78148,194833,96278,98555
10,文山,43,43,997,997,103349,274129,132016,142113
11,南港,20,20,454,452,45923,121386,59280,62106
12,內湖,39,39,907,906,105468,286047,137050,148997
13,士林,51,51,990,989,105599,290649,140594,150055
14,北投,42,42,827,826,95094,257604,124480,133124
15,說明：自103年2月起里鄰數係根據戶籍登記資料里鄰門牌資料檔及戶籍登記資料分列（與行政區域編...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [258]:
# 刪除不必要欄位
aaa= df.drop(["Unnamed: 1", "Unnamed: 2"], axis=1)

In [259]:
# 整理欄位名稱
aaa=aaa.rename(columns={aaa.columns[0]: '區',
                        "Unnamed: 3": "戶數",
                    "Unnamed: 4":"男人口數",
                    "Unnamed: 5":"女人口數",
                    "Unnamed: 6":"總人口數"})

In [260]:
# 整理多餘row
aaa=aaa.drop([0,1])

In [261]:
# 增加年份資訊
aaa['年份']=103

In [262]:
aaa

     區       戶數     男人口數     女人口數     總人口數   年份
2   總計  1027004  1290558  1397582  2688140  103
3   松山    79797    99512   110899   210411  103
4   信義    88435   109727   118894   228621  103
5   大安   119437   146907   166554   313461  103
6   中山    97352   107081   121845   228926  103
7   中正    64607    78235    85000   163235  103
8   大同    50580    63632    66317   129949  103
9   萬華    77223    95795    97663   193458  103
10  文山   101965   130961   140594   271555  103
11  南港    45109    58697    61258   119955  103
12  內湖   103858   135803   147282   283085  103
13  士林   104779   140457   149441   289898  103
14  北投    93862   123751   131835   255586  103

In [263]:
aaa['性別比']=aaa['男人口數']/aaa['女人口數']

In [264]:
aaa=aaa.drop(['男人口數','女人口數'], axis=1)

In [266]:
aaa.to_csv("103_pop.csv",index=None)

In [265]:
aaa

     區       戶數     總人口數   年份       性別比
2   總計  1027004  2688140  103  0.923422
3   松山    79797   210411  103  0.897321
4   信義    88435   228621  103  0.922898
5   大安   119437   313461  103  0.882038
6   中山    97352   228926  103   0.87883
7   中正    64607   163235  103  0.920412
8   大同    50580   129949  103  0.959513
9   萬華    77223   193458  103  0.980873
10  文山   101965   271555  103  0.931484
11  南港    45109   119955  103  0.958193
12  內湖   103858   283085  103  0.922061
13  士林   104779   289898  103  0.939883
14  北投    93862   255586  103  0.938681