In [1]:
import pandas as pd

In [2]:
df = pd.read_xml('CCI.xml')

In [3]:
df

                            Item TIME_PERIOD FREQ    TYPE  Item_VALUE
0            營造工程總指數(民國105年=100)     1991M01    M     原始值       53.45
1            營造工程總指數(民國105年=100)     1991M01    M  年增率(%)         NaN
2         一.營造工程_材料類(民國105年=100)     1991M01    M     原始值       47.03
3         一.營造工程_材料類(民國105年=100)     1991M01    M  年增率(%)         NaN
4         (一)水泥及其製品類(民國105年=100)     1991M01    M     原始值       63.20
...                          ...         ...  ...     ...         ...
21803  土木工程_下水道工程總指數(民國105年=100)     2022M04    M  年增率(%)        9.45
21804  土木工程_自來水工程總指數(民國105年=100)     2022M04    M     原始值      124.72
21805  土木工程_自來水工程總指數(民國105年=100)     2022M04    M  年增率(%)        9.53
21806   土木工程_治水工程總指數(民國105年=100)     2022M04    M     原始值      133.18
21807   土木工程_治水工程總指數(民國105年=100)     2022M04    M  年增率(%)       10.09

[21808 rows x 5 columns]

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 21808 entries, 0 to 21807
Data columns (total 5 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Item         21808 non-null  object
 1   TIME_PERIOD  21808 non-null  object
 2   FREQ         21808 non-null  object
 3   TYPE         21808 non-null  object
 4   Item_VALUE   18676 non-null  float64
dtypes: float64(1), object(4)
memory usage: 852.0+ KB

In [5]:
df['year']=df['TIME_PERIOD'].str.split("M").str.get(0)
df['month']=df['TIME_PERIOD'].str.split("M").str.get(1)

In [6]:
df['year'] = df['year'].astype('int')
df['month'] = df['month'].astype('int')

In [7]:
df

,Item,TIME_PERIOD,FREQ,TYPE,Item_VALUE,year,month
0,營造工程總指數(民國105年=100),1991M01,M,原始值,53.45,1991,1
1,營造工程總指數(民國105年=100),1991M01,M,年增率(%),NaN,1991,1
2,一.營造工程_材料類(民國105年=100),1991M01,M,原始值,47.03,1991,1
3,一.營造工程_材料類(民國105年=100),1991M01,M,年增率(%),NaN,1991,1
4,(一)水泥及其製品類(民國105年=100),1991M01,M,原始值,63.20,1991,1
...,...,...,...,...,...,...,...
21803,土木工程_下水道工程總指數(民國105年=100),2022M04,M,年增率(%),9.45,2022,4
21804,土木工程_自來水工程總指數(民國105年=100),2022M04,M,原始值,124.72,2022,4
21805,土木工程_自來水工程總指數(民國105年=100),2022M04,M,年增率(%),9.53,2022,4
21806,土木工程_治水工程總指數(民國105年=100),2022M04,M,原始值,133.18,2022,4
21807,土木工程_治水工程總指數(民國105年=100),2022M04,M,年增率(%),10.09,2022,4

In [8]:
# 觀察有哪些項目
df[df['TIME_PERIOD'] == '1991M01']

,Item,TIME_PERIOD,FREQ,TYPE,Item_VALUE,year,month
0,營造工程總指數(民國105年=100),1991M01,M,原始值,53.45,1991,1
1,營造工程總指數(民國105年=100),1991M01,M,年增率(%),NaN,1991,1
2,一.營造工程_材料類(民國105年=100),1991M01,M,原始值,47.03,1991,1
3,一.營造工程_材料類(民國105年=100),1991M01,M,年增率(%),NaN,1991,1
4,(一)水泥及其製品類(民國105年=100),1991M01,M,原始值,63.20,1991,1
5,(一)水泥及其製品類(民國105年=100),1991M01,M,年增率(%),NaN,1991,1
6,(二)砂石及級配類(民國105年=100),1991M01,M,原始值,19.38,1991,1
7,(二)砂石及級配類(民國105年=100),1991M01,M,年增率(%),NaN,1991,1
8,(三)磚瓦瓷類(民國105年=100),1991M01,M,原始值,61.58,1991,1
9,(三)磚瓦瓷類(民國105年=100),1991M01,M,年增率(%),NaN,1991,1
10,(四)金屬製品類(民國105年=100),1991M01,M,原始值,64.62,1991,1
11,(四)金屬製品類(民國105年=100),1991M01,M,年增率(%),NaN,1991,1
12,(五)木材及其製品類(民國105年=100),1991M01,M,原始值,37.03,1991,1
13,(五)木材及其製品類(民國105年=100),1991M01,M,年增率(%),NaN,1991,1
14,(六)塑膠製品類(民國105年=100),1991M01,M,原始值,58.52,1991,1
15,(六)塑膠製品類(民國105年=100),1991M01,M,年增率(%),NaN,1991,1
16,(七)油漆塗裝類(民國105年=100),1991M01,M,原始值,50.04,1991,1
17,(七)油漆塗裝類(民國105年=100),1991M01,M,年增率(%),NaN,1991,1
18,(八)機電設備類(民國105年=100),1991M01,M,原始值,64.03,1991,1
19,(八)機電設備類(民國105年=100),1991M01,M,年增率(%),NaN,1991,1
20,(九)瀝青及其製品類(民國105年=100),1991M01,M,原始值,25.05,1991,1
21,(九)瀝青及其製品類(民國105年=100),1991M01,M,年增率(%),NaN,1991,1
22,(十)雜項類(民國105年=100),1991M01,M,原始值,64.07,1991,1
23,(十)雜項類(民國105年=100),1991M01,M,年增率(%),NaN,1991,1
24,二.營造工程_勞務類(民國105年=100),1991M01,M,原始值,70.11,1991,1
25,二.營造工程_勞務類(民國105年=100),1991M01,M,年增率(%),NaN,1991,1
26,(一)工資類(民國105年=100),1991M01,M,原始值,75.20,1991,1
27,(一)工資類(民國105年=100),1991M01,M,年增率(%),NaN,1991,1
28,(二)機具設備租金類(民國105年=100),1991M01,M,原始值,59.43,1991,1
29,(二)機具設備租金類(民國105年=100),1991M01,M,年增率(%),NaN,1991,1
30,建築工程總指數(民國105年=100),1991M01,M,原始值,60.91,1991,1
31,建築工程總指數(民國105年=100),1991M01,M,年增率(%),NaN,1991,1
32,一.建築工程_材料類(民國105年=100),1991M01,M,原始值,57.36,1991,1
33,一.建築工程_材料類(民國105年=100),1991M01,M,年增率(%),NaN,1991,1
34,二.建築工程_勞務類(民國105年=100),1991M01,M,原始值,71.35,1991,1
35,二.建築工程_勞務類(民國105年=100),1991M01,M,年增率(%),NaN,1991,1
36,建築工程_鋼筋混凝土工程總指數(民國105年=100),1991M01,M,原始值,NaN,1991,1
37,建築工程_鋼筋混凝土工程總指數(民國105年=100),1991M01,M,年增率(%),NaN,1991,1
38,建築工程_鋼骨鋼筋混凝土工程總指數(民國105年=100),1991M01,M,原始值,NaN,1991,1
39,建築工程_鋼骨鋼筋混凝土工程總指數(民國105年=100),1991M01,M,年增率(%),NaN,1991,1
40,建築工程_鋼骨構造工程總指數(民國105年=100),1991M01,M,原始值,NaN,1991,1
41,建築工程_鋼骨構造工程總指數(民國105年=100),1991M01,M,年增率(%),NaN,1991,1
42,土木工程總指數(民國105年=100),1991M01,M,原始值,48.07,1991,1
43,土木工程總指數(民國105年=100),1991M01,M,年增率(%),NaN,1991,1
44,一.土木工程_材料類(民國105年=100),1991M01,M,原始值,40.46,1991,1
45,一.土木工程_材料類(民國105年=100),1991M01,M,年增率(%),NaN,1991,1
46,二.土木工程_勞務類(民國105年=100),1991M01,M,原始值,68.81,1991,1
47,二.土木工程_勞務類(民國105年=100),1991M01,M,年增率(%),NaN,1991,1
48,土木工程_公路工程總指數(民國105年=100),1991M01,M,原始值,NaN,1991,1
49,土木工程_公路工程總指數(民國105年=100),1991M01,M,年增率(%),NaN,1991,1
50,土木工程_橋梁工程總指數(民國105年=100),1991M01,M,原始值,NaN,1991,1
51,土木工程_橋梁工程總指數(民國105年=100),1991M01,M,年增率(%),NaN,1991,1
52,土木工程_下水道工程總指數(民國105年=100),1991M01,M,原始值,NaN,1991,1
53,土木工程_下水道工程總指數(民國105年=100),1991M01,M,年增率(%),NaN,1991,1
54,土木工程_自來水工程總指數(民國105年=100),1991M01,M,原始值,NaN,1991,1
55,土木工程_自來水工程總指數(民國105年=100),1991M01,M,年增率(%),NaN,1991,1
56,土木工程_治水工程總指數(民國105年=100),1991M01,M,原始值,NaN,1991,1
57,土木工程_治水工程總指數(民國105年=100),1991M01,M,年增率(%),NaN,1991,1

In [9]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 21808 entries, 0 to 21807
Data columns (total 7 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Item         21808 non-null  object
 1   TIME_PERIOD  21808 non-null  object
 2   FREQ         21808 non-null  object
 3   TYPE         21808 non-null  object
 4   Item_VALUE   18676 non-null  float64
 5   year         21808 non-null  int32
 6   month        21808 non-null  int32
dtypes: float64(1), int32(2), object(4)
memory usage: 1022.4+ KB

In [10]:
# 只抓總指數出來
df = df[df['Item'] == '營造工程總指數(民國105年=100)']

In [11]:
df

                      Item TIME_PERIOD FREQ    TYPE  Item_VALUE  year  month
0      營造工程總指數(民國105年=100)     1991M01    M     原始值       53.45  1991      1
1      營造工程總指數(民國105年=100)     1991M01    M  年增率(%)         NaN  1991      1
58     營造工程總指數(民國105年=100)     1991M02    M     原始值       53.55  1991      2
59     營造工程總指數(民國105年=100)     1991M02    M  年增率(%)         NaN  1991      2
116    營造工程總指數(民國105年=100)     1991M03    M     原始值       53.42  1991      3
...                    ...         ...  ...     ...         ...   ...    ...
21635  營造工程總指數(民國105年=100)     2022M02    M  年增率(%)       10.03  2022      2
21692  營造工程總指數(民國105年=100)     2022M03    M     原始值      130.10  2022      3
21693  營造工程總指數(民國105年=100)     2022M03    M  年增率(%)       11.37  2022      3
21750  營造工程總指數(民國105年=100)     2022M04    M     原始值      132.48  2022      4
21751  營造工程總指數(民國105年=100)     2022M04    M  年增率(%)       11.81  2022      4

[752 rows x 7 columns]

In [12]:
# 篩選出 2012~2021 年
df = df[ df['year'] >= 2012 ]
df = df[ df['year'] <= 2021 ]

In [13]:
df

                      Item TIME_PERIOD FREQ    TYPE  Item_VALUE  year  month
14616  營造工程總指數(民國105年=100)     2012M01    M     原始值      102.80  2012      1
14617  營造工程總指數(民國105年=100)     2012M01    M  年增率(%)        1.73  2012      1
14674  營造工程總指數(民國105年=100)     2012M02    M     原始值      102.98  2012      2
14675  營造工程總指數(民國105年=100)     2012M02    M  年增率(%)        1.50  2012      2
14732  營造工程總指數(民國105年=100)     2012M03    M     原始值      103.31  2012      3
...                    ...         ...  ...     ...         ...   ...    ...
21403  營造工程總指數(民國105年=100)     2021M10    M  年增率(%)       13.36  2021     10
21460  營造工程總指數(民國105年=100)     2021M11    M     原始值      125.81  2021     11
21461  營造工程總指數(民國105年=100)     2021M11    M  年增率(%)       13.19  2021     11
21518  營造工程總指數(民國105年=100)     2021M12    M     原始值      125.68  2021     12
21519  營造工程總指數(民國105年=100)     2021M12    M  年增率(%)       11.31  2021     12

[240 rows x 7 columns]

In [14]:
# 刪除不需要的欄位
df = df.drop(['Item', 'TIME_PERIOD','FREQ'], axis=1)

In [15]:
df

         TYPE  Item_VALUE  year  month
14616     原始值      102.80  2012      1
14617  年增率(%)        1.73  2012      1
14674     原始值      102.98  2012      2
14675  年增率(%)        1.50  2012      2
14732     原始值      103.31  2012      3
...       ...         ...   ...    ...
21403  年增率(%)       13.36  2021     10
21460     原始值      125.81  2021     11
21461  年增率(%)       13.19  2021     11
21518     原始值      125.68  2021     12
21519  年增率(%)       11.31  2021     12

[240 rows x 4 columns]

In [16]:
rate = df[df['TYPE'] == '年增率(%)']
CCI = df[df['TYPE'] == '原始值']

In [17]:
rate['Item_VALUE'].unique()
# 年增率有負數，代表通貨緊縮

array([ 1.730e+00,  1.500e+00,  8.900e-01,  2.050e+00,  2.260e+00,
        1.520e+00,  1.010e+00,  5.900e-01, -3.300e-01, -1.010e+00,
       -1.000e-02, -1.500e-01,  9.000e-02,  1.700e-01,  1.000e-02,
       -1.430e+00, -2.120e+00, -1.770e+00, -1.170e+00, -8.400e-01,
        3.500e-01,  9.200e-01,  8.200e-01,  7.900e-01,  6.000e-01,
        4.700e-01,  1.590e+00,  2.250e+00,  2.980e+00,  3.170e+00,
        3.120e+00,  2.510e+00,  2.030e+00,  1.020e+00,  2.800e-01,
       -3.900e-01, -6.900e-01, -1.530e+00, -2.240e+00, -2.790e+00,
       -3.700e+00, -4.380e+00, -4.470e+00, -4.700e+00, -4.590e+00,
       -4.610e+00, -4.430e+00, -4.080e+00, -2.390e+00, -1.280e+00,
       -1.870e+00, -1.490e+00, -9.600e-01, -9.700e-01, -5.000e-01,
        2.700e-01,  2.300e+00,  2.610e+00,  2.960e+00,  1.480e+00,
        2.200e-01,  1.610e+00,  2.740e+00,  3.710e+00,  3.860e+00,
        3.540e+00,  2.790e+00,  2.720e+00,  2.420e+00,  2.500e+00,
        3.000e+00,  3.920e+00,  4.200e+00,  4.550e+00,  3.690e+00,
        3.350e+00,  3.820e+00,  3.280e+00,  2.820e+00,  2.370e+00,
        3.450e+00,  3.440e+00,  2.850e+00,  2.630e+00,  2.010e+00,
        1.950e+00,  1.350e+00,  1.000e+00,  1.700e+00,  1.920e+00,
        9.600e-01,  6.700e-01,  1.300e-01,  4.100e-01,  5.700e-01,
        8.300e-01,  1.780e+00,  2.460e+00,  2.800e+00,  3.950e+00,
        6.010e+00,  6.170e+00,  7.070e+00,  9.100e+00,  1.155e+01,
        1.303e+01,  1.371e+01,  1.357e+01,  1.302e+01,  1.336e+01,
        1.319e+01,  1.131e+01])

In [18]:
CCI['Item_VALUE'].unique()

array([102.8 , 102.98, 103.31, 104.32, 104.64, 103.99, 103.41, 103.24,
       102.48, 101.89, 102.25, 102.38, 102.89, 103.16, 103.32, 102.83,
       102.42, 102.15, 102.2 , 102.37, 102.84, 103.09, 103.7 , 103.78,
       103.81, 104.46, 104.72, 105.19, 105.44, 105.56, 105.42, 104.92,
       104.37, 103.38, 102.86, 102.26, 101.54, 100.94, 100.71,  99.99,
        99.84,  99.56,  99.38,  99.16,  99.28, 100.4 , 101.06, 100.35,
       100.03,  99.97,  99.73,  99.49, 100.11, 101.05, 101.67, 101.75,
       102.22, 101.28, 101.37, 101.64, 102.71, 103.43, 103.33, 103.65,
       103.87, 104.44, 104.21, 104.78, 104.95, 105.25, 105.63, 106.26,
       106.5 , 106.9 , 107.28, 107.05, 106.8 , 106.92, 107.81, 108.38,
       108.47, 108.25, 108.41, 108.4 , 108.58, 108.34, 107.92, 108.12,
       108.62, 108.97, 108.85, 109.11, 108.61, 108.69, 109.03, 109.05,
       109.48, 110.27, 110.58, 111.15, 112.91, 115.52, 115.57, 116.82,
       118.49, 121.24, 123.24, 124.  , 124.34, 124.63, 125.35, 125.81,
       125.68])

In [19]:
CCI

      TYPE  Item_VALUE  year  month
14616  原始值      102.80  2012      1
14674  原始值      102.98  2012      2
14732  原始值      103.31  2012      3
14790  原始值      104.32  2012      4
14848  原始值      104.64  2012      5
...    ...         ...   ...    ...
21286  原始值      124.34  2021      8
21344  原始值      124.63  2021      9
21402  原始值      125.35  2021     10
21460  原始值      125.81  2021     11
21518  原始值      125.68  2021     12

[120 rows x 4 columns]

In [20]:
rate

         TYPE  Item_VALUE  year  month
14617  年增率(%)        1.73  2012      1
14675  年增率(%)        1.50  2012      2
14733  年增率(%)        0.89  2012      3
14791  年增率(%)        2.05  2012      4
14849  年增率(%)        2.26  2012      5
...       ...         ...   ...    ...
21287  年增率(%)       13.57  2021      8
21345  年增率(%)       13.02  2021      9
21403  年增率(%)       13.36  2021     10
21461  年增率(%)       13.19  2021     11
21519  年增率(%)       11.31  2021     12

[120 rows x 4 columns]

In [21]:
# 新增和房價的一樣格式的時間欄位 

CCI['ROC_year'] =  (CCI['year']-1911)*100 + CCI['month']
rate['ROC_year'] =  (rate['year']-1911)*100 + rate['month']

CCI = CCI.drop(['TYPE','year','month'], axis=1)
rate = rate.drop(['TYPE','year','month'], axis=1)

C:\Users\Student\AppData\Local\Temp/ipykernel_20404/2081361504.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  CCI['ROC_year'] =  (CCI['year']-1911)*100 + CCI['month']
C:\Users\Student\AppData\Local\Temp/ipykernel_20404/2081361504.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  rate['ROC_year'] =  (rate['year']-1911)*100 + rate['month']

In [22]:
CCI.rename(columns = {'Item_VALUE':'CCI'}, inplace = True)

rate.rename(columns = {'Item_VALUE':'CCI_rate'}, inplace = True)

In [23]:
CCI

          CCI  ROC_year
14616  102.80     10101
14674  102.98     10102
14732  103.31     10103
14790  104.32     10104
14848  104.64     10105
...       ...       ...
21286  124.34     11008
21344  124.63     11009
21402  125.35     11010
21460  125.81     11011
21518  125.68     11012

[120 rows x 2 columns]

In [24]:
rate

       CCI_rate  ROC_year
14617      1.73     10101
14675      1.50     10102
14733      0.89     10103
14791      2.05     10104
14849      2.26     10105
...         ...       ...
21287     13.57     11008
21345     13.02     11009
21403     13.36     11010
21461     13.19     11011
21519     11.31     11012

[120 rows x 2 columns]

In [25]:
# merge 方法可以指定欄位合併
CCI_final = pd.merge(CCI, rate, on='ROC_year')

In [26]:
CCI_final

        CCI  ROC_year  CCI_rate
0    102.80     10101      1.73
1    102.98     10102      1.50
2    103.31     10103      0.89
3    104.32     10104      2.05
4    104.64     10105      2.26
..      ...       ...       ...
115  124.34     11008     13.57
116  124.63     11009     13.02
117  125.35     11010     13.36
118  125.81     11011     13.19
119  125.68     11012     11.31

[120 rows x 3 columns]

In [27]:
# 轉換成main dataframe一樣的欄位方便合併
CCI_final.rename(columns = {'ROC_year':'date'}, inplace = True)

In [28]:
CCI_final.to_csv("CCI.csv", index=False)